apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: geparcedemy-ci
  description: "geparcedemy"
  tags:
    - kustomize
    - argocd
  links:
    - url: https://localhost:8080
      title: WebApp Endpoint
      icon: web
  annotations:
    'github.com/project-slug': gattma/geparcedemy-ci
    'backstage.io/kubernetes-id': geparcedemy-ci
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/gepardec"
  system: gepardemy