apiVersion: apps/v1
kind: Deployment
metadata:
  name: geparcedemy-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: geparcedemy
        image: ghcr.io/gattma/geparcedemy:master-06d37ff
        ports:
        - containerPort: 8080